name: Deploy

on:
  # workflow_dispatch
  push
env:
  SERVER_HOST: 51.38.73.150
  SERVER_USER: root
  SERVER_PATH: /opt/test_git
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Install ssh key
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: "${{ secrets.DEPLOY_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"          
      
      - name: Generate auth hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy to server      
        run: |
           ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "cd /opt/bot-weather-git && docker stop bot-weather-git_app_1 && docker-compose up -d"
  
 

  
  
